export default {
  name: 'MixinProjects',
  data() {
    return {
      projects: [
        {
          name: 'Dando by CFG',
          type: 'web',
          key: 'dando',
          url: 'https://www.dando.co/es',
          company: 'Modyo',
        },
        {
          name: 'PWA - Cinemark',
          type: 'pwa',
          key: 'pwa-cinemark',
          url: null,
          company: 'Modyo',
        },
        {
          name: 'BCI Miami',
          type: 'web',
          key: 'bci-miami',
          url: null,
          company: 'Modyo',
        },
        {
          name: 'Superdigital',
          type: 'web',
          key: 'superdigital',
          url: 'https://www.superdigital.cl/',
          company: 'Modyo',
        },
        {
          name: 'Consorcio',
          type: 'web',
          key: 'consorcio',
          url: 'https://web.consorcio.cl/home',
          company: 'Modyo',
        },
        {
          name: 'Copec',
          type: 'web',
          key: 'copec',
          url: 'https://ww2.copec.cl/',
          company: 'Modyo',
        },
        {
          name: 'Santander',
          type: 'web',
          key: 'santander',
          url: 'https://banco.santander.cl/personas',
          company: 'Modyo',
        },
        {
          name: 'Vías Chile',
          type: 'api & web',
          key: 'vias-chile-web',
          url: 'https://obras.viaschile.cl/inicio',
          company: 'DevLab',
          img: 'vias-chile.png',
          size: 'small',
        },
        {
          name: 'Pago Click',
          type: 'app',
          key: 'pago-click',
          url: null,
          company: 'Modyo',
        },
        {
          name: 'App Cinemark Chile',
          type: 'app',
          key: 'app-cinemark-chile',
          url: 'https://apps.apple.com/cl/app/cinemark-chile/id1401507945',
          company: 'Modyo',
        },
        {
          name: 'Cinemark Chile',
          type: 'web',
          key: 'cinemark-chile',
          url: 'https://www.cinemark.cl/',
          company: 'Modyo',
        },
        {
          name: 'Cinemark Paraguay',
          type: 'web',
          key: 'cinemark-paraguay',
          url: 'https://www.cinemark.com.py/',
          company: 'Modyo',
        },
        {
          name: 'Cinemark Bolivia',
          type: 'web',
          key: 'cinemark-bolivia',
          url: 'https://www.cinemark.com.bo/',
          company: 'Modyo',
        },
        {
          name: 'Cinemark Perú',
          type: 'web',
          key: 'cinemark-peru',
          url: 'https://www.cinemark-peru.com/',
          company: 'Modyo',
        },
        {
          name: 'Cinemark Colombia',
          type: 'web',
          key: 'cinemark-colombia',
          url: 'https://www.cinemark.com.co/',
          company: 'Modyo',
        },
        {
          name: 'BCI Personas',
          type: 'web',
          key: 'bci-personas',
          url: 'https://www.bci.cl/personas',
          company: 'Modyo',
        },
        {
          name: 'Sencillito',
          type: 'web',
          key: 'sencillito',
          url: 'https://www.sencillito.com/',
          company: 'Modyo',
        },
        {
          name: 'Cocha',
          type: 'web',
          key: 'cocha',
          url: 'https://www.cocha.com/',
          company: 'Modyo',
        },
        {
          name: 'Mundo Copec',
          type: 'app',
          key: 'app-mundo-copec',
          url: 'https://ww2.copec.cl/informate/posts/descargue-la-app-mundo-copec',
          company: 'Techmobile',
        },
        {
          name: 'Tribuna Centenario',
          type: 'app',
          key: 'app-tribuna-centenario',
          url: 'https://edgares.com/tribuna-centenario',
          company: 'Techmobile',
        },
        {
          name: 'Bioscell',
          type: 'web',
          key: 'bioscell',
          url: 'https://bioscell.cl/',
          company: 'Techmobile',
        },
        {
          name: 'Marina Golf Rapel',
          type: 'web',
          key: 'marina-golf-rapel',
          url: 'https://marinagolfrapel.cl/',
          company: 'Techmobile',
        },
        {
          name: 'IMS',
          type: 'api, web & app',
          key: 'app-ims-web',
          url: 'https://www.industrialms.cl/',
          company: 'DevLab',
        },
        {
          name: 'Aygcamp',
          type: 'api & app',
          key: 'app-aygcamp-app',
          url: null,
          company: 'DevLab',
        },
      ],
    };
  },
};
